export enum BytemineCountries {
	'Angola',
	'Benin',
	'Algeria',
	'Botswana',
	'Burkina Faso',
	'Burundi',
	'Cameroon',
	'Cape Verde',
	'Central African Republic',
	'Chad',
	'Comoros',
	'Democratic Republic Of The Congo',
	'Djibouti',
	'Egypt',
	'Equatorial Guinea',
	'Eritrea',
	'Ethiopia',
	'Gabon',
	'Gambia',
	'Ghana',
	'Guinea',
	'Guinea-Bissau',
	'Kenya',
	'Lesotho',
	'Liberia',
	'Libya',
	'Madagascar',
	'Malawi',
	'Mali',
	'Mauritania',
	'Mauritius',
	'Mayotte',
	'Morocco',
	'Mozambique',
	'Namibia',
	'Niger',
	'Nigeria',
	'Republic Of The Congo',
	'Rwanda',
	'Senegal',
	'Seychelles',
	'Sierra Leone',
	'Somalia',
	'South Africa',
	'South Sudan',
	'Sudan',
	'Swaziland',
	'Tanzania',
	'Togo',
	'Tunisia',
	'Uganda',
	'Western Sahara',
	'Zambia',
	'Zimbabwe',
	'Antarctica',
	'Bouvet Island',
	'French Southern Territories',
	'Heard Island And Mcdonald Islands',
	'South Georgia And The South Sandwich Islands',
	'Afghanistan',
	'Armenia',
	'Azerbaijan',
	'Bahrain',
	'Bangladesh',
	'Bhutan',
	'British Indian Ocean Territory',
	'Brunei',
	'Cambodia',
	'China',
	'Christmas Island',
	'Georgia',
	'Hong Kong',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Israel',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Lebanon',
	'Macau',
	'Malaysia',
	'Maldives',
	'Mongolia',
	'Myanmar',
	'Nepal',
	'North Korea',
	'Oman',
	'Pakistan',
	'Palestine',
	'Philippines',
	'Qatar',
	'Sã£O Tomã© And Prã',
	'Saudi Arabia',
	'Singapore',
	'South Korea',
	'Sri Lanka',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Thailand',
	'Timor-Leste',
	'Turkey',
	'Turkmenistan',
	'United Arab Emirates',
	'Uzbekistan',
	'Vietnam',
	'Yemen',
	'Albania',
	'Andorra',
	'Austria',
	'Belarus',
	'Belgium',
	'Bosnia And Herzegovina',
	'Bulgaria',
	'Croatia',
	'Cyprus',
	'Czechia',
	'Denmark',
	'Estonia',
	'Faroe Islands',
	'Finland',
	'France',
	'Germany',
	'Gibraltar',
	'Greece',
	'Guernsey',
	'Hungary',
	'Iceland',
	'Ireland',
	'Isle Of Man',
	'Italy',
	'Jersey',
	'Kosovo',
	'Latvia',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Macedonia',
	'Malta',
	'Moldova',
	'Monaco',
	'Montenegro',
	'Netherlands',
	'Norway',
	'Poland',
	'Portugal',
	'Romania',
	'Russia',
	'San Marino',
	'Serbia',
	'Slovakia',
	'Slovenia',
	'Spain',
	'Svalbard And Jan Mayen',
	'Sweden',
	'Switzerland',
	'Ukraine',
	'United Kingdom',
	'Vatican City',
	'Anguilla',
	'Antigua And Barbuda',
	'Aruba',
	'Bahamas',
	'Barbados',
	'Belize',
	'Bermuda',
	'British Virgin Islands',
	'Canada',
	'Caribbean Netherlands',
	'Cayman Islands',
	'Costa Rica',
	'Cuba',
	'Curaã§Ao',
	'Dominica',
	'Dominican Republic',
	'El Salvador',
	'Greenland',
	'Grenada',
	'Guadeloupe',
	'Guatemala',
	'Haiti',
	'Honduras',
	'Jamaica',
	'Martinique',
	'Mexico',
	'Montserrat',
	'Netherlands Antilles',
	'Nicaragua',
	'Panama',
	'Puerto Rico',
	'Saint Helena',
	'Saint Kitts And Nevis',
	'Saint Lucia',
	'Saint Martin',
	'Saint Pierre And Miquelon',
	'Saint Vincent And The Grenadines',
	'Sint Maarten',
	'Trinidad And Tobago',
	'Turks And Caicos Islands',
	'U.S. Virgin Islands',
	'United States',
	'American Samoa',
	'Australia',
	'Cocos (Keeling) Islands',
	'Cook Islands',
	'Fiji',
	'French Polynesia',
	'Guam',
	'Kiribati',
	'Marshall Islands',
	'Micronesia',
	'Nauru',
	'New Caledonia',
	'New Zealand',
	'Niue',
	'Norfolk Island',
	'Northern Mariana Islands',
	'Palau',
	'Papua New Guinea',
	'Pitcairn',
	'Samoa',
	'Solomon Islands',
	'Tokelau',
	'Tonga',
	'Tuvalu',
	'United States Minor Outlying Islands',
	'Vanuatu',
	'Wallis And Futuna',
	'Argentina',
	'Bolivia',
	'Brazil',
	'Chile',
	'Colombia',
	'Ecuador',
	'Falkland Islands',
	'French Guiana',
	'Guyana',
	'Paraguay',
	'Peru',
	'Suriname',
	'Uruguay',
	'Venezuela',
}

export const BytemineCountryOptions = Object.entries(BytemineCountries)
	.filter((type: [string, string]) => typeof type[1] === 'string')
	.map((type: [string, string]) => ({
		value: type[1],
		label: type[1],
	}));
