export enum BytemineTitlesToIgnore {
	'Sales',
	'Revenue',
	'Account Executive',
	'Business Development',
	'CRO',
	'CSO',
	'Salesforce',
	'Customer Success',
	'Sales Operations',
	'C.S.O.',
	'C.R.O.',
	'Marketing',

	'Lead Generation',
	'CMO',
	'C.M.O.',
	'P.R.',
	'Brand',
	'Communications',
	'Public Relations',
	'Press Relations',
	'Social Media',
	'PR',
	'Digital',
	'Product',
	'Web Designer',
	'Graphic Designer',
	'SEO',
	'Content',
	'Media',
	'S.E.O.',
	'Information Technology',

	'IT',
	'I.T.',
	'Software Developer',
	'Software Development',
	'Network Admin',
	'Network Administrator',
	'Help Desk',
	'Systems Analyst',
	'Network Engineer',
	'Web Developer',
	'Technology',
	'Information',
	'CTO',
	'CIO',
	'C.T.O',
	'C.I.O',
	'User Experience',
	'Data Scientist',
	'DevOps',
	'Software Engineer',
	'Programmer',
	'Cloud Architect',
	'Application Developer',
	'Technical Specialist',
	'SQL',
	'UX Designer',
	'Quality Assurance',
	'QA',
	'Data Architect',
	'.net',
	'tech support',
	'User Testing',
	'Finance',
	'Accounts Payable',
	'Accounts Receivable',
	'Treasury',
	'CFO',
	'C.F.O',
	'Treasurer',
	'Accountant',
	'BookKeeper',
	'Financial',
	'Procurement',
	'Banking',
	'Controller',
	'Budget',
	'Comptroller',
	'Auditor',
	'Contracts',
	'Grants',
	'Payroll',
	'Accounting',
	'Economist',
	'Actuary',
	'Investment',
	'financial',
	'Human Resources',
	'HR',
	'H.R.',
	'Benefits',
	'Staffing',
	'Recruiting',
	'Training',
	'Compensation',
	'CHRO',
	'C.H.R.O.',
	'Chief People',
	'Recruiter',
	'Employee Relations',
	'Talent',
	'Employment',
	'Human Resource',
	'Personnel',
	'People',

	'Legal',
	'Attorney',
	'Paralegal',
	'Lawyer',
	'esquire',
	'counsel',

	'Operations',
	'COO',
	'Innovation',
	'Researcher',
	'Planning',
	'Business Analyst',
	'strategy',
	'Logistics',
	'Supply Chain',
	'R&D',
	'Research',
}

export const BytemineTitlesToIgnoreOptions = Object.entries(BytemineTitlesToIgnore)
	.filter((type: [string, string]) => typeof type[1] === 'string')
	.map((type: [string, string]) => ({
		value: type[1],
		label: type[1],
	}));
